### PR TITLE
[DDO-1606] Add a GitHub action to push images to GCR

### PR DESCRIPTION
**Pull request by jack-r-warren**
Copied from Revere/Sherlock and adapted to reference GCR variables (as a small handrail against copy-pasting in the future) and exclude go-related things. Does a Trivy scan.

Also see https://github.com/broadinstitute/openidc-proxy/pull/28

### CODE REVIEW

**Comment by jack-r-warren** [comment]
Draft because this breaks without https://github.com/broadinstitute/terraform-ap-deployments/pull/439

**Review by mikeflinn — APPROVED** [review]

**Comment by nmalfroy** [comment]
Could this actually make things more compliant because it runs Trivy?

**Comment by mikeflinn** [comment]
> Could this actually make things more compliant because it runs Trivy?

My suspicion is appSec may have been scanning this image in some manner, as it likely predates our use of trivy. But it certainly won't hurt :)

**Comment by jack-r-warren** [comment]
So, the action seems to be working. But the build itself is failing, it can't resolve `static.tcell.io` and neither can my browser. @nmalfroy I'll try to get through this today but it is a bit of an unexpected roadblock

**Comment by nmalfroy** [comment]
Oh right…I think tcell may be deprecated since they were acquired?

**Comment by jack-r-warren** [comment]
Closing this since according to https://broadinstitute.slack.com/archives/CADM7MZ35/p1634222793141300?thread_ts=1634137067.113800&cid=CADM7MZ35 we should not touch this and we don't need to

**Pull request closed without merging**
